# Generated by Django 3.2.13 on 2022-04-13 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0023_uk_domicile_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('modified_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('moodle_id', models.IntegerField(error_messages={'unique': 'Moodle ID already in use'}, unique=True, verbose_name='Moodle ID')),
                ('first_module_code', models.CharField(blank=True, max_length=12, null=True)),
                ('student', models.OneToOneField(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, related_name='moodle_id', to='student.student')),
            ],
            options={
                'verbose_name': 'Moodle ID',
                'db_table': 'moodle_id',
            },
        ),
    ]
