# Generated by Django 3.0.13 on 2021-03-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorfee',
            name='raised_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tutorfee',
            name='status',
            field=models.ForeignKey(db_column='status', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor_payment.TutorFeeStatus'),
        ),
    ]
