# Generated by Django 3.2.7 on 2021-09-20 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor_payment', '0003_alter_tutorfee_raised_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorfee',
            name='approver',
            field=models.ForeignKey(db_column='approver', on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver_payments', related_query_name='approver_payment', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='tutorfee',
            name='raised_by',
            field=models.ForeignKey(db_column='raised_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_payments', related_query_name='tutor_payment', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='tutorfeestatus',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorfeetype',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tutorfeetype',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tutorfeetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
