# Generated by Django 3.2.7 on 2021-09-21 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_tutor_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor_payment', '0004_auto_20210920_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorFeeRate',
            new_name='PaymentRate',
        ),
        migrations.RenameModel(
            old_name='TutorFeeStatus',
            new_name='PaymentStatus',
        ),
        migrations.RenameModel(
            old_name='TutorFeeType',
            new_name='PaymentType',
        ),
        migrations.RenameModel(
            old_name='TutorFee',
            new_name='TutorPayment',
        ),
    ]
