repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]  # handle !! constructors in mkdocs.yml
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude_types: [svg]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==21.4.3
          - flake8-builtins==1.5.3
          - flake8-comprehensions==3.5.0
          - flake8-django==1.1.2
          - flake8-eradicate==1.1.0
          - flake8-print==4.0.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.4.1
    hooks:
     - id: eslint
       args: [--fix]
       exclude: ckeditor/plugins/
