repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-yaml
        exclude: mkdocs.yml  # doesn't like !! tags
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude_types: [svg]

  - repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==21.4.3
          - flake8-builtins==1.5.3
          - flake8-comprehensions==3.5.0
          - flake8-django==1.1.2
          - flake8-eradicate==1.1.0
          - flake8-print==4.0.0
