version: "3.8"

services:
  django:
    image: redpot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - source: app_config
        target: /code/secrets.json
    ports:
      - "8001-8002:8000"
    deploy:
      mode: replicated
      replicas: 2
    restart: always

  worker:
    image: redpot:latest
    secrets:
      - source: app_config
        target: /code/secrets.json
    restart: always
    command: celery -A redpot worker -n redpot-worker

  redis:
    image: redis:6.0
    restart: always

secrets:
  app_config:
    file: ./secrets.json
