version: "3.8"

services:
  django:
    image: redpot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - source: app_config
        target: /code/secrets.json
    ports:
      - "8000:8000"
    restart: always

  worker:
    image: redpot:latest
    secrets:
      - source: app_config
        target: /code/secrets.json
    restart: always
    command: celery -A redpot worker -n redpot-worker

  redis:
    image: redis:6.0
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - MSSQL_SA_PASSWORD=Test@only
     - ACCEPT_EULA=Y

secrets:
  app_config:
    file: ./secrets.json
