site_name: Redpot unchained documentation
repo_name: oudce/redpot-unchained
repo_url: https://gitlab.conted.ox.ac.uk/django/redpot-unchained
edit_uri: edit/master/docs/

site_dir: static/docs

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/gitlab
    logo: material/book-open-page-variant
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - How to:
    - Invoices: invoices.md
    - Enrolments: enrolment.md
  - About: about.md
  - Development:
      - Development principles: development-principles.md
      - Style guide: style-guide.md
      - Common patterns: common-patterns.md
      - Pre-commit hooks: pre-commit-hooks.md
      - App file structure: app-structure.md
      - Gotchas: gotchas.md
      - Moving models: moving-models.md

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
