site_name: Redpot unchained docs!
repo_name: oudce/redpot-unchained
repo_url: https://gitlab.conted.ox.ac.uk/django/redpot-unchained
edit_uri: edit/master/docs/

site_dir: static/docs

google_analytics: ['gaid', 'url']

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/gitlab
    logo: material/book-open-page-variant
  palette:
    scheme: preference

nav:
  - Home: index.md
  - How to:
    - Invoices: invoices.md
    - Enrolments: enrolment.md
  - About: about.md
  - Development:
      - Development principles: development-principles.md
      - Style guide: style-guide.md
      - App file structure: app-structure.md
      - Gotchas: gotchas.md

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
