[tool.isort]
known_django = 'django'
line_length = 119
sections = 'FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER'
skip = ['migrations', '.venv']

# black-compatible configs
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
line-length = 119
target-version = ['py37']
skip-string-normalization = true
extend-exclude = 'migrations'

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'redpot.settings'
