[tool.isort]
known_django = 'django'
line_length = 119
sections = 'FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER'
skip = ['migrations', '.venv']

# black-compatible configs
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
line-length = 119
target-version = ['py37']
skip-string-normalization = true
force-exclude = 'migrations'  # ensures migrations ignored even during pre-commit hooks

[tool.mypy]
plugins = ['mypy_django_plugin.main']
ignore_missing_imports = true
exclude = '(migrations|tests|automodels.py)'
check_untyped_defs = true

[tool.django-stubs]
django_settings_module = "redpot.settings"
