# Generated by Django 3.0.11 on 2021-02-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        ('module', '0004_auto_20210218_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=256, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=256, null=True)),
                ('nino', models.CharField(blank=True, max_length=64, null=True)),
                ('employee_no', models.CharField(blank=True, max_length=32, null=True)),
                ('appointment_id', models.CharField(blank=True, max_length=32, null=True)),
                ('bankname', models.CharField(blank=True, max_length=64, null=True)),
                ('branchaddress', models.CharField(blank=True, max_length=128, null=True)),
                ('accountname', models.CharField(blank=True, max_length=64, null=True)),
                ('sortcode', models.CharField(blank=True, max_length=8, null=True)),
                ('accountno', models.CharField(blank=True, max_length=32, null=True)),
                ('swift', models.CharField(blank=True, max_length=11, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('other_bank_details', models.CharField(blank=True, max_length=512, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('rtw_check_on', models.DateField(blank=True, null=True)),
                ('rtw_check_by', models.CharField(blank=True, max_length=50, null=True)),
                ('rtw_start_date', models.DateField(blank=True, null=True)),
                ('rtw_end_date', models.DateField(blank=True, null=True)),
                ('oracle_supplier_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='TutorModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('role', models.CharField(blank=True, max_length=64, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_teaching', models.BooleanField(default=True)),
                ('director_of_studies', models.BooleanField(default=False)),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_modules', to='module.Module')),
                ('tutor', models.ForeignKey(db_column='tutor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_modules', to='tutor.Tutor')),
            ],
            options={
                'verbose_name': 'Tutor on module',
                'db_table': 'tutor_module',
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='modules',
            field=models.ManyToManyField(related_name='tutors', through='tutor.TutorModule', to='module.Module'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='student',
            field=models.OneToOneField(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student'),
        ),
    ]
