# Generated by Django 3.0.14 on 2021-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodule',
            name='biography',
            field=models.TextField(blank=True, help_text='When filled, this overrides the default tutor biography for this module only', null=True),
        ),
        migrations.AlterField(
            model_name='tutormodule',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Display on the website?'),
        ),
        migrations.AlterField(
            model_name='tutormodule',
            name='role',
            field=models.CharField(blank=True, help_text="e.g. 'Tutor' or 'Speaker'", max_length=64),
        ),
    ]
