# Generated by Django 3.0.13 on 2021-04-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20210404_2005'),
        ('tutor', '0002_auto_20210225_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodule',
            name='module',
            field=models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_modules', related_query_name='tutor_module', to='module.Module'),
        ),
        migrations.AlterField(
            model_name='tutormodule',
            name='tutor',
            field=models.ForeignKey(db_column='tutor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_modules', related_query_name='tutor_module', to='tutor.Tutor'),
        ),
    ]
