# Generated by Django 3.2.5 on 2021-07-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20210722_1228'),
        ('tutor', '0004_auto_20210701_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=64, null=True)),
                ('subject', models.ForeignKey(blank=True, db_column='subject', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutorsubjects', to='module.subject')),
                ('tutor', models.ForeignKey(blank=True, db_column='tutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutorsubjects', to='tutor.tutor')),
            ],
            options={
                'db_table': 'tutor_subject',
            },
        ),
        migrations.CreateModel(
            name='TutorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=16, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=16, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, db_column='activity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_activities', to='tutor.activitytype')),
                ('tutor', models.ForeignKey(blank=True, db_column='tutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_activities', to='tutor.tutor')),
            ],
            options={
                'db_table': 'tutor_activity',
            },
        ),
    ]
