# Generated by Django 3.2.6 on 2021-08-09 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_activitytype_tutoractivity_tutorsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoractivity',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tutoractivity',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tutoractivity',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tutoractivity',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubject',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubject',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubject',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsubject',
            name='modified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
    ]
