# Generated by Django 3.2.6 on 2021-08-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_alter_subject_options'),
        ('tutor', '0006_auto_20210809_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(blank=True, through='tutor.TutorSubject', to='module.Subject'),
        ),
    ]
