# Generated by Django 3.2.7 on 2021-09-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_tutor_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['rtw_document_type'], 'permissions': [('edit_bank_details', "Can view and edit a tutor's banking details")]},
        ),
    ]
