# Generated by Django 3.2.7 on 2021-10-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_alter_tutor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='righttoworkdocumenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': [('edit_bank_details', "Can view and edit a tutor's banking details")]},
        ),
    ]
