# Generated by Django 3.2.8 on 2021-10-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20211006_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tutoractivity',
            name='activity',
            field=models.ForeignKey(db_column='activity', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_activities', to='tutor.activitytype'),
        ),
        migrations.AlterField(
            model_name='tutoractivity',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tutoractivity',
            name='note',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='tutoractivity',
            name='tutor',
            field=models.ForeignKey(db_column='tutor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_activities', to='tutor.tutor'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
