# Generated by Django 3.2.8 on 2021-10-19 12:21

import apps.tutor.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_correct_activity_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.tutor.models.get_image_filename),
        ),
    ]
