# Generated by Django 3.2.8 on 2021-10-19 12:21

import imagekit.models.fields

from django.db import migrations

import apps.tutor.models
import redpot.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_correct_activity_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, storage=redpot.storage_backends.WebsiteStorage(), upload_to=apps.tutor.models.get_image_filename),
        ),
    ]
