# Generated by Django 3.2.12 on 2022-03-10 16:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_alter_tutor_image'),
    ]

    operations = [
        # migration split so it doesn't try to apply a default uuid value to the database
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='tutor',
                    name='hash_id',
                    field=models.UUIDField(editable=False, null=True),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='tutor',
                    name='hash_id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
            ]
        )
    ]
