# Generated by Django 3.2.12 on 2022-03-14 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_tutor_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='nino',
            field=models.CharField(blank=True, error_messages={'unique': 'National Insurance number already in use'}, help_text='Enter without spaces, e.g. <i>AB123456C</i>', max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{6}[A-Z]$', message='Must be in the form AB123456C')], verbose_name='National insurance #'),
        ),
    ]
