# Generated by Django 3.0.14 on 2021-05-06 10:39

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False, null=True, blank=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('modified_on', models.DateTimeField(default=datetime.datetime.now, editable=False, null=True, blank=True)),
                ('name', models.TextField()),
                ('code', models.CharField(max_length=20, unique=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('module_mask', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='DiscountStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('redeemed', models.BooleanField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                (
                    'discount',
                    models.ForeignKey(
                        db_column='discount',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='students',
                        related_query_name='student',
                        to='discount.Discount',
                    ),
                ),
            ],
            options={
                'db_table': 'discount_student',
            },
        ),
    ]
