# Generated by Django 3.0.14 on 2021-05-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme', '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='portfolio',
            field=models.ForeignKey(
                blank=True,
                db_column='portfolio',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='programme.Portfolio',
            ),
        ),
    ]
