# Generated by Django 3.2.7 on 2021-09-27 10:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_image'),
        ('discount', '0002_discount_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='module_mask',
            field=models.CharField(help_text='Limits the discount to modules matching the pattern, e.g. <i>O2[0123]P%V</i>', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='portfolio',
            field=models.ForeignKey(blank=True, db_column='portfolio', help_text='Optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.portfolio'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='usable_once',
            field=models.BooleanField(default=False, verbose_name='Usable only once?'),
        ),
        migrations.AlterField(
            model_name='discountstudent',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
