# Generated by Django 3.2.7 on 2021-09-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discount_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='usable_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountstudent',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
