# Generated by Django 3.2.13 on 2022-04-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20210927_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountStudent',
        ),
    ]
