# Generated by Django 3.2.5 on 2021-07-14 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210708_1429'),
        ('enrolment', '0005_auto_20210614_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
                ('is_hidden', models.BooleanField()),
            ],
            options={
                'db_table': 'ledger_account',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
                ('is_cash', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'transaction_type',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_column='date')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('finance_code', models.CharField(blank=True, max_length=64, null=True)),
                ('narrative', models.CharField(max_length=128)),
                ('account', models.ForeignKey(db_column='account', limit_choices_to={'is_hidden': False}, on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('allocation', models.IntegerField()),
                ('ref_no', models.IntegerField(blank=True, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('division', models.ForeignKey(blank=True, db_column='division', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.division')),
                ('enrolment', models.ForeignKey(blank=True, db_column='enrolment', null=True, on_delete=django.db.models.deletion.PROTECT, to='enrolment.enrolment')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='finance.transactiontype')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
            ],
            options={
                'db_table': 'ledger',
            },
        ),
    ]
