# Generated by Django 3.2.6 on 2021-08-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrolment', '0005_auto_20210614_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmendmentStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('icon', models.TextField()),
            ],
            options={
                'db_table': 'amendment_status',
            },
        ),
        migrations.CreateModel(
            name='AmendmentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('action', models.TextField()),
                ('supported', models.BooleanField()),
            ],
            options={
                'db_table': 'amendment_type',
            },
        ),
        migrations.CreateModel(
            name='AmendmentReason',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='amendment.amendmenttype')),
            ],
            options={
                'db_table': 'amendment_reason',
            },
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField()),
                ('requested_by', models.TextField()),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.TextField(blank=True, null=True)),
                ('executed_on', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.TextField(blank=True, null=True)),
                ('approver', models.CharField(blank=True, max_length=16, null=True)),
                ('transfer_module', models.TextField(blank=True, null=True)),
                ('invoice', models.IntegerField(blank=True, null=True)),
                ('source_invoice', models.IntegerField(blank=True, null=True)),
                ('transfer_invoice', models.IntegerField(blank=True, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('narrative', models.CharField(max_length=128)),
                ('is_complete', models.BooleanField(default=False)),
                ('actioned_online', models.BooleanField(default=False)),
                ('enrolment', models.ForeignKey(db_column='enrolment', on_delete=django.db.models.deletion.DO_NOTHING, related_name='amendments', related_query_name='amendment', to='enrolment.enrolment')),
                ('reason', models.ForeignKey(db_column='reason', on_delete=django.db.models.deletion.DO_NOTHING, to='amendment.amendmentreason')),
                ('status', models.ForeignKey(db_column='status', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='amendment.amendmentstatus')),
                ('transfer_enrolment', models.ForeignKey(blank=True, db_column='transfer_enrolment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enrolment.enrolment')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='amendment.amendmenttype')),
            ],
            options={
                'db_table': 'amendment',
                'permissions': [('approve', 'Approve finance change requests')],
            },
        ),
    ]
