# Generated by Django 3.2.5 on 2021-07-08 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme', '0007_auto_20210623_1644'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'staff_role',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('note', models.CharField(blank=True, max_length=64, null=True)),
                ('programme', models.ForeignKey(db_column='programme', on_delete=django.db.models.deletion.CASCADE, related_name='programme_staff_set', to='programme.programme')),
                ('role', models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='staff_list.staffrole')),
                ('staff', models.ForeignKey(db_column='staff', on_delete=django.db.models.deletion.CASCADE, related_name='programme_staff_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programme_staff',
            },
        ),
    ]
