# Generated by Django 3.2.10 on 2022-01-06 13:13

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0020_alter_student_options'),
        ('module', '0014_delete_waitlist'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Waitlist',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('listed_on', models.DateTimeField(default=datetime.datetime.now)),
                        ('emailed_on', models.DateTimeField(blank=True, null=True)),
                        ('module',
                         models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING,
                                           related_name='waitlists', to='module.module')),
                        ('student',
                         models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING,
                                           related_name='waitlists', to='student.student')),
                    ],
                    options={
                        'db_table': 'module_waitlist',
                    },
                ),
            ],
            database_operations=[]
        ),
    ]
