# Generated by Django 3.0.11 on 2021-02-04 16:34

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'qualification.yaml', verbosity=2)


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
