# Generated by Django 3.0.14 on 2021-05-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='reporting_year_type',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
