# Generated by Django 3.0.14 on 2021-05-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_auto_20210513_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='entry_qualification',
            field=models.ForeignKey(db_column='entry_qualification', default='X06', on_delete=django.db.models.deletion.DO_NOTHING, to='programme.EntryQualification'),
        ),
    ]
