# Generated by Django 3.0.11 on 2021-02-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_load_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studylocation',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studylocation',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
    ]
