# Generated by Django 3.0.14 on 2021-05-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_auto_20210523_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='study_location',
            field=models.ForeignKey(db_column='study_location', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='programme.StudyLocation'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='study_location',
            field=models.ForeignKey(db_column='study_location', default=1,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='programme.StudyLocation'),
        ),
    ]
