# Generated by Django 3.0.11 on 2021-02-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20210218_1342'),
        ('programme', '0003_auto_20210211_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmemodule',
            name='module',
            field=models.ForeignKey(db_column='module', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programme_modules', to='module.Module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programmemodule',
            name='programme',
            field=models.ForeignKey(db_column='programme', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programme_modules', to='programme.Programme'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='programmemodule',
            unique_together={('programme', 'module')},
        ),
    ]
