# Generated by Django 3.0.11 on 2021-02-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_auto_20210218_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='division',
            field=models.ForeignKey(db_column='division', default=1, limit_choices_to=models.Q(('id__gt', 8), ('id__lt', 5), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='programme.Division'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='portfolio',
            field=models.ForeignKey(db_column='portfolio', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='programme.Portfolio'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='qualification',
            field=models.ForeignKey(db_column='qualification', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='programme.Qualification'),
        ),
    ]
