# Generated by Django 3.0.14 on 2021-06-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_auto_20210608_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ('title',), 'permissions': [('edit_registry_fields', 'Can edit programme fields like Study Location or Student Load (should just be one programme.edit permission'), ('edit_restricted_fields', 'Can edit dev-restricted fields (is_active, contact_list_display, sits_id')]},
        ),
        migrations.AlterField(
            model_name='programme',
            name='study_location',
            field=models.ForeignKey(db_column='study_location', default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='programme.StudyLocation'),
        ),
    ]
