# Generated by Django 3.0.14 on 2021-06-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_auto_20210614_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='sits_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='SITS code'),
        ),
    ]
