# Generated by Django 3.2.13 on 2022-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0008_alter_programme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='data_futures_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
