# Generated by Django 3.2.13 on 2022-04-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesa', '0006_admin_config'),
        ('programme', '0009_qualification_data_futures_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='hecos_subjects',
            field=models.ManyToManyField(through='hesa.ProgrammeHecosSubject', to='hesa.HECoSSubject'),
        ),
    ]
