# Generated by Django 3.2.5 on 2021-07-22 12:28

import apps.core.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'populate_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to=apps.core.models.PathAndRename('images/staff_profile/')),
        ),
    ]
