# Generated by Django 3.2.8 on 2021-10-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_approver',
            field=models.ForeignKey(blank=True, db_column='default_approver', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
