# Generated by Django 3.2.5 on 2021-07-22 12:28

import imagekit

from django.db import migrations

import apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'populate_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.core.models.get_profile_image_filename),
        ),
    ]
