# Generated by Django 3.2.9 on 2021-11-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_default_approver'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE SEQUENCE [invoice_number_sequence]
                AS [int]
                START WITH 1
                INCREMENT BY 1
            """
        ),
        migrations.RunSQL(
            """
            CREATE SEQUENCE [ledger_allocation_sequence]
                AS [int]
                START WITH 1
                INCREMENT BY 1
            """
        ),
        migrations.RunSQL(
            """
            CREATE SEQUENCE [ledger_batch_sequence]
                AS [int]
                START WITH 1
                INCREMENT BY 1
            """
        ),
    ]
