# Generated by Django 3.2.12 on 2022-02-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userrightssupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
