# Generated by Django 3.2.12 on 2022-03-10 16:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_externalmenuitem'),
    ]

    operations = [
        # migration split so it doesn't try to apply a default uuid value to the database
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='user',
                    name='hash_id',
                    field=models.UUIDField(editable=False, null=True),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='hash_id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
            ]
        )
    ]
