# Generated by Django 3.2.10 on 2022-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRightsSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('print', 'Can print an individual student transcript'), ('batch_print', 'Can produce batches of transcripts')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
