version: "3.9"
services:
  django:
    image: ${REDPOT_IMAGE:?}
    secrets:
      - source: app_config
        target: /code/secrets.env
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
    healthcheck:
      test: curl localhost:8000/  # todo: a lightweight /healthcheck endpoint
      interval: "15s"  # compromise between quick "start" and long "running" healthchecks.  Docker doesn't let you pick both
      timeout: "3s"
      retries: 3
    ports:
      - 8000:8000
    user: ${REDPOT_DOCKER_USER}  # uid:gid for permissions on bind mounts
    entrypoint: ["/code/docker/prod_static_entrypoint.sh", "uwsgi"]
    volumes:
      - ${STATIC_FOLDER:?}/static:/volumes/static
      - ${STATIC_FOLDER:?}/media:/volumes/media

  worker:
    image: ${REDPOT_IMAGE:?}
    secrets:
      - source: app_config
        target: /code/secrets.env
    # beats embedded, since we use one worker node.  to scale up the worker containers, add a separate beats container
    command: celery -A redpot worker --beat
    deploy:
      update_config:
        order: stop-first  # avoid multiple beats processes
        failure_action: rollback
    user: ${REDPOT_DOCKER_USER}  # uid:gid for permissions on bind mounts
    volumes:
      - ${STATIC_FOLDER:?}/media:/volumes/media

  redis:
    image: redis:6.0
    deploy:
      update_config:
        order: start-first
        failure_action: rollback

secrets:
  app_config:
    file: ../secrets.env
    name: settings-${SETTINGS_TIMESTAMP:-0}
