# Generated by Django 3.0.14 on 2021-05-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
        ('fee', '0001_initial'),
        ('enrolment', '0002_auto_20210506_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='module',
            field=models.ForeignKey(
                db_column='module',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='fees',
                to='module.Module',
            ),
        ),
        migrations.AddField(
            model_name='fee',
            name='type',
            field=models.ForeignKey(
                db_column='type',
                default=7,
                limit_choices_to={'is_active': True},
                on_delete=django.db.models.deletion.PROTECT,
                to='fee.FeeType',
            ),
        ),
        migrations.AddField(
            model_name='catering',
            name='enrolment',
            field=models.ForeignKey(
                db_column='enrolment',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='catering',
                to='enrolment.Enrolment',
            ),
        ),
        migrations.AddField(
            model_name='catering',
            name='fee',
            field=models.ForeignKey(
                db_column='fee', on_delete=django.db.models.deletion.PROTECT, related_name='catering', to='fee.Fee'
            ),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='enrolment',
            field=models.ForeignKey(
                db_column='enrolment', on_delete=django.db.models.deletion.PROTECT, to='enrolment.Enrolment', related_name='accommodation'
            ),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='limit',
            field=models.ForeignKey(
                blank=True,
                db_column='limit',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bookings',
                related_query_name='booking',
                to='fee.Limit',
            ),
        ),
    ]
