# Generated by Django 3.2.5 on 2021-07-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('fee', '0003_auto_20210506_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='account',
            field=models.ForeignKey(db_column='account', on_delete=django.db.models.deletion.PROTECT, to='finance.account'),
            preserve_default=False,
        ),
    ]
