# Generated by Django 3.2.7 on 2021-10-01 19:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0008_auto_20210907_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('person', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(db_column='module', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='module.module')),
            ],
            options={
                'db_table': 'feedback_admin',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_tutor', models.IntegerField(blank=True, null=True)),
                ('rate_content', models.IntegerField(blank=True, null=True)),
                ('rate_admin', models.IntegerField(blank=True, null=True)),
                ('rate_facilities', models.IntegerField(blank=True, null=True)),
                ('rate_refreshments', models.IntegerField(blank=True, null=True)),
                ('rate_accommodation', models.IntegerField(blank=True, null=True)),
                ('your_name', models.TextField(blank=True, null=True)),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notified', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.DateTimeField(blank=True, null=True)),
                ('avg_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(db_column='module', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='module.module')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
