# Generated by Django 3.2.7 on 2021-09-28 16:40

import apps.core.utils.json
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0007_tutor_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('type', models.CharField(choices=[('casual', 'Casual teaching contract'), ('guest', 'Guest speaker letter')], max_length=32)),
                ('options', models.JSONField(decoder=apps.core.utils.json.ExtendedJSONDecoder, encoder=apps.core.utils.json.ExtendedJSONEncoder)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Awaiting approval'), (3, 'Approved by manager, awaiting signature'), (4, 'Signed by Department'), (5, 'Signed and returned by tutor'), (6, 'Cancelled')], db_column='status', default=1)),
                ('received_on', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=32, null=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=32, null=True)),
                ('signed_on', models.DateTimeField(blank=True, null=True)),
                ('email_notification', models.EmailField(blank=True, help_text='Enter your email address to be notified when the contract is signed by the departmental signatory', max_length=32, null=True)),
                ('approver', models.ForeignKey(db_column='approver', on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver_contracts', related_query_name='approver_contract', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Approving manager')),
                ('tutor_module', models.ForeignKey(db_column='tutor_module', on_delete=django.db.models.deletion.PROTECT, to='tutor.tutormodule')),
            ],
            options={
                'db_table': 'tutor_contract',
                'permissions': [('approve', 'Can be assigned and approve tutor contracts')],
            },
        ),
    ]
