# Generated by Django 3.2.7 on 2021-09-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_tutor_subjects'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tutor_module',
            field=models.ForeignKey(db_column='tutor_module', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', related_query_name='contract', to='tutor.tutormodule'),
        ),
    ]
