# Generated by Django 3.2.6 on 2021-09-01 14:27

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50, unique=True)),
                ('system_email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('modified_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Required if known. If not known, you can update it later. The staff will be flagged for update.', max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date(if known)')),
                ('is_a_member_of_TSS', models.BooleanField(blank=True, verbose_name='Is a member of TSS?')),
                ('replacing', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone Ext.')),
                ('overseas_calls', models.BooleanField(blank=True, verbose_name='Overseas call?')),
                ('uni_card_number', models.CharField(blank=True, help_text='Required for an external email routing', max_length=50)),
                ('shared_accounts', models.TextField(blank=True, help_text='Shared mailboxes that need to be accessed. Provide mailbox names.', null=True, verbose_name='Shared Mailbox Accounts')),
                ('shared_folders', models.TextField(blank=True, help_text='Network folders that need to be accessed. Provide drive letter and sub-folders.', null=True)),
                ('others', models.TextField(blank=True, help_text='Provide any further information or requests.', null=True)),
                ('sso', models.CharField(blank=True, max_length=50, verbose_name='Uni SSO')),
                ('flags', models.ManyToManyField(blank=True, to='staff_forms.Flag')),
                ('mailing_lists', models.ManyToManyField(blank=True, to='staff_forms.MailingList')),
                ('section', models.ForeignKey(blank=True, db_column='section', on_delete=django.db.models.deletion.DO_NOTHING, to='staff_forms.section')),
                ('systems', models.ManyToManyField(blank=True, to='staff_forms.System')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
