# Generated by Django 3.2.6 on 2021-09-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_image'),
        ('staff_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starter',
            name='section',
        ),
        migrations.AddField(
            model_name='starter',
            name='division',
            field=models.ForeignKey(blank=True, db_column='division', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.division'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
