# Generated by Django 3.2.10 on 2022-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_sequences'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRightsSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('finance', 'Generic finance-team rights'), ('marketing', 'Generic marketing-team rights')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
