# Generated by Django 3.2.7 on 2021-10-05 13:03

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrolment', '0007_auto_20210929_2148'),
        ('fee', '0004_feetype_account'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Limit',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                        ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                        ('modified_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                        ('modified_on', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                        ('description', models.CharField(max_length=128)),
                        ('places', models.IntegerField()),
                        ('www_buffer', models.IntegerField(default=0, help_text='Spaces that cannot be booked online')),
                    ],
                    options={
                        'db_table': 'limit',
                    },
                ),
                migrations.CreateModel(
                    name='Catering',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                        ('created_on',
                         models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                        ('modified_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                        ('modified_on',
                         models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                        ('enrolment',
                         models.ForeignKey(db_column='enrolment', on_delete=django.db.models.deletion.PROTECT,
                                           related_name='catering', to='enrolment.enrolment')),
                        ('fee', models.ForeignKey(db_column='fee', on_delete=django.db.models.deletion.PROTECT,
                                                  related_name='catering', to='fee.fee')),
                    ],
                    options={
                        'db_table': 'catering',
                    },
                ),
                migrations.CreateModel(
                    name='Accommodation',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                        ('created_on',
                         models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                        ('modified_by', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                        ('modified_on',
                         models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                        (
                        'type', models.IntegerField(choices=[(None, ' - Select - '), (100, 'Single'), (200, 'Twin')])),
                        ('note', models.CharField(blank=True, max_length=256, null=True)),
                        ('enrolment',
                         models.ForeignKey(db_column='enrolment', on_delete=django.db.models.deletion.PROTECT,
                                           related_name='accommodation', to='enrolment.enrolment')),
                        ('limit', models.ForeignKey(blank=True, db_column='limit', null=True,
                                                    on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='bookings', related_query_name='booking',
                                                    to='booking.limit')),
                    ],
                    options={
                        'db_table': 'accommodation',
                    },
                ),
            ],
            database_operations=[]
        ),
    ]
