# Generated by Django 3.2.7 on 2021-10-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limit',
            old_name='www_buffer',
            new_name='online_booking_buffer',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='limit',
            field=models.ForeignKey(blank=True, db_column='limit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', related_query_name='booking', to='booking.limit'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='online_booking_buffer',
            field=models.IntegerField(db_column='www_buffer', default=0, help_text='Spaces that cannot be booked online'),
        ),
    ]
