# Generated by Django 3.0.14 on 2021-06-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesa', '0002_2021_changes'),
        ('qualification_aim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertHEMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('courses_transferred_in', models.TextField(blank=True, null=True)),
                ('credits_transferred_in', models.IntegerField(blank=True, null=True)),
                ('assignment1_date', models.DateField(blank=True, null=True)),
                ('assignment1_grade', models.IntegerField(blank=True, null=True)),
                ('assignment2_date', models.DateField(blank=True, null=True)),
                ('assignment2_grade', models.IntegerField(blank=True, null=True)),
                ('assignment3_date', models.DateField(blank=True, null=True)),
                ('assignment3_grade', models.IntegerField(blank=True, null=True)),
                ('journal1_date', models.DateField(blank=True, null=True)),
                ('journal2_date', models.DateField(blank=True, null=True)),
                ('journal_cats_points', models.IntegerField(blank=True, null=True)),
                ('is_introductory_course', models.BooleanField(blank=True, null=True)),
                ('qualification_aim', models.OneToOneField(db_column='qa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='certhe_marks', to='qualification_aim.QualificationAim')),
                ('subject', models.ForeignKey(blank=True, db_column='subject', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hesa.HECoSSubject')),
            ],
            options={
                'db_table': 'certhe_marks',
            },
        ),
    ]
