# Generated by Django 3.2.5 on 2021-07-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210623_1644'),
        ('qualification_aim', '0001_squashed_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationaim',
            name='student',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, related_name='qas', related_query_name='qa', to='student.student'),
        ),
    ]
