# Generated by Django 3.2.5 on 2021-07-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210722_1228'),
        ('qualification_aim', '0002_alter_qualificationaim_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationaim',
            name='entry_qualification',
            field=models.ForeignKey(blank=True, db_column='entry_qualification', limit_choices_to=models.Q(('web_publish', True), ('id__in', ['X00', 'X06']), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qualification_aims', to='qualification_aim.entryqualification'),
        ),
        migrations.AlterField(
            model_name='qualificationaim',
            name='reason_for_ending',
            field=models.ForeignKey(blank=True, db_column='reason_for_ending', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qualification_aims', to='qualification_aim.reasonforending'),
        ),
        migrations.AlterField(
            model_name='qualificationaim',
            name='student',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, related_name='qualification_aims', related_query_name='qa', to='student.student'),
        ),
    ]
