# Generated by Django 3.0.14 on 2021-06-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_auto_20210623_1644'),
        ('qualification_aim', '0002_certhemarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonForEnding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'reason_for_ending',
            },
        ),
        migrations.AddField(
            model_name='qualificationaim',
            name='sits_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='SITS code'),
        ),
        migrations.AlterField(
            model_name='qualificationaim',
            name='study_location',
            field=models.ForeignKey(db_column='study_location', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='programme.StudyLocation'),
        ),
        migrations.AddField(
            model_name='qualificationaim',
            name='reason_for_ending',
            field=models.ForeignKey(blank=True, db_column='reason_for_ending', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qualification_aim.ReasonForEnding'),
        ),
    ]
