# Generated by Django 3.2.7 on 2021-09-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_auto_20210623_1644'),
        ('qualification_aim', '0003_auto_20210722_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationaim',
            name='programme',
            field=models.ForeignKey(db_column='programme', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_aims', to='programme.programme'),
        ),
    ]
