# Generated by Django 3.2.13 on 2022-04-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_aim', '0004_alter_qualificationaim_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryqualification',
            name='data_futures_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
