# Generated by Django 3.0.11 on 2021-02-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husid', models.BigIntegerField(blank=True, null=True)),
                ('surname', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('middlename', models.CharField(blank=True, max_length=40, null=True)),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('domicile', models.IntegerField(blank=True, null=True)),
                ('nationality', models.IntegerField(blank=True, null=True)),
                ('ethnicity', models.IntegerField(blank=True, null=True)),
                ('religion_or_belief', models.IntegerField(default=99)),
                ('disability', models.IntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=128, null=True)),
                ('termtime_postcode', models.CharField(blank=True, max_length=32, null=True)),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
                ('no_publicity', models.BooleanField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_eu', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=16, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=16, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('deceased', models.BooleanField(blank=True, db_column='Deceased', null=True)),
                ('disability_detail', models.CharField(blank=True, max_length=2048, null=True)),
                ('disability_action', models.CharField(blank=True, max_length=256, null=True)),
                ('dars_optout', models.BooleanField(default=True)),
                ('termtime_accommodation', models.IntegerField(blank=True, null=True)),
                ('sits_id', models.IntegerField(blank=True, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=128, null=True)),
                ('mail_optin', models.BooleanField(default=False)),
                ('mail_optin_on', models.DateTimeField(blank=True, null=True)),
                ('mail_optin_method', models.CharField(blank=True, max_length=64, null=True)),
                ('email_optin', models.BooleanField(default=False)),
                ('email_optin_method', models.CharField(blank=True, max_length=64, null=True)),
                ('email_optin_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
