# Generated by Django 3.0.11 on 2021-03-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='husid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='HUSID'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=128, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails', related_query_name='email', to='student.Student')),
            ],
            options={
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.IntegerField(choices=[(100, 'Permanent'), (110, 'Home'), (111, 'Next of Kin'), (400, 'College'), (410, 'Oxford College'), (500, 'Work'), (510, 'Work - Line Manager')], db_column='type', default=100)),
                ('line1', models.CharField(max_length=128)),
                ('line2', models.CharField(blank=True, max_length=128, null=True)),
                ('line3', models.CharField(blank=True, max_length=128, null=True)),
                ('town', models.CharField(blank=True, max_length=64, null=True)),
                ('countystate', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=32, null=True)),
                ('formatted', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_default', models.BooleanField()),
                ('is_billing', models.BooleanField(blank=True, null=True)),
                ('sits_type', models.CharField(blank=True, editable=False, max_length=1, null=True)),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', related_query_name='address', to='student.Student')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
