# Generated by Django 3.0.13 on 2021-04-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210301_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
