# Generated by Django 3.0.14 on 2021-06-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_aim', '0002_certhemarks'),
        ('student', '0003_auto_20210513_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='highest_qualification',
            field=models.ForeignKey(blank=True, db_column='highest_qualification', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qualification_aim.EntryQualification'),
        ),
    ]
