# Generated by Django 3.0.14 on 2021-06-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_aim', '0003_auto_20210623_1644'),
        ('student', '0004_highest_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='highest_qualification',
            field=models.ForeignKey(blank=True, db_column='highest_qualification', limit_choices_to={'web_publish': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qualification_aim.EntryQualification'),
        ),
    ]
