# Generated by Django 3.2.5 on 2021-07-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210722_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ethnicity',
            field=models.ForeignKey(db_column='ethnicity', default=90, on_delete=django.db.models.deletion.DO_NOTHING, to='student.ethnicity'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=32, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, db_column='student', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
            options={
                'db_table': 'emergency_contact',
            },
        ),
    ]
