# Generated by Django 3.2.7 on 2021-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210809_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='countystate',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='County/state'),
        ),
        migrations.AlterField(
            model_name='address',
            name='formatted',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_billing',
            field=models.BooleanField(default=False, verbose_name='Billing?'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=True, verbose_name='Default?'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line3',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Line 3'),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='City/town'),
        ),
    ]
