# Generated by Django 3.2.7 on 2021-09-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_domicile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default?'),
        ),
        migrations.AlterField(
            model_name='moodleid',
            name='first_module_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='moodleid',
            name='moodle_id',
            field=models.IntegerField(error_messages={'unique': 'Moodle ID already in use'}, unique=True),
        ),
        migrations.AlterField(
            model_name='otherid',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='student.otheridtype'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default?'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.ForeignKey(db_column='type', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.phonetype'),
        ),
    ]
