# Generated by Django 3.2.7 on 2021-09-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_domicile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Other'), ('', 'Unknown')], max_length=1, null=True),
        ),
    ]
