# Generated by Django 3.2.7 on 2021-09-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20210907_2208'),
        ('student', '0014_auto_20210921_1357'),
    ]

    operations = [
    ]
