# Generated by Django 3.2.7 on 2021-09-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_merge_0012_auto_20210907_2208_0014_auto_20210921_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherid',
            name='number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='otherid',
            name='type',
            field=models.IntegerField(choices=[(None, ' –– Choose one –– '), (1, 'Student Bar code ID'), (2, 'Passport ID'), (3, 'Visa ID'), (4, 'HESA ID'), (5, 'Regulatory Body Ref. Number (eg. GMC)'), (6, 'Unique Learner Number (ULN)'), (7, 'SSO username'), (8, 'OSS person number'), (9, 'Student support number'), (10, 'Alumni number')]),
        ),
    ]
