# Generated by Django 3.2.7 on 2021-10-01 20:04

from django.db import migrations, models

import apps.core.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20210923_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='type',
            field=models.IntegerField(blank=True, choices=[(None, 'None'), (200, 'Vegetarian'), (210, 'Vegan'), (220, 'Fish-eating vegetarian'), (230, 'Demi-vegetarian (no red meat)'), (240, 'Non-dairy'), (250, 'Diabetic'), (320, 'Gluten Free (Coeliac)'), (900, 'Other')], db_column='type', null=True, verbose_name='Special diet'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=apps.core.utils.models.PhoneField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=apps.core.utils.models.PhoneField(max_length=64),
        ),
        migrations.DeleteModel(
            name='DietType',
        ),
    ]
