# Generated by Django 3.2.7 on 2021-09-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20210923_1250'),
        ('student', '0016_auto_20210924_1628'),
    ]

    operations = [
    ]
