# Generated by Django 3.2.8 on 2021-11-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20211116_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('merge_student', 'Merge student records'), ('view_restricted_fields', 'Can View and Edit restricted fields')], 'verbose_name': 'Person'},
        ),
    ]
