# Generated by Django 3.2.10 on 2022-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_optin',
            field=models.BooleanField(default=False, verbose_name='Email marketing'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_optin_method',
            field=models.CharField(blank=True, choices=[('Application form', 'Application form'), ('Email', 'Email'), ('Email_resubscribe', 'Email resubscribe link'), ('In_person', 'In-person'), ('Newsletter', 'Newsletter widget'), ('Other', 'Other form'), ('Phone', 'Phone'), ('Website', 'Website optin')], help_text='How did this person sign up to receive marketing email?', max_length=47, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mail_optin',
            field=models.BooleanField(default=False, verbose_name='Mail marketing'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mail_optin_method',
            field=models.CharField(blank=True, choices=[('Application form', 'Application form'), ('Email', 'Email'), ('Email_resubscribe', 'Email resubscribe link'), ('In_person', 'In-person'), ('Newsletter', 'Newsletter widget'), ('Other', 'Other form'), ('Phone', 'Phone'), ('Website', 'Website optin')], max_length=47, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='no_publicity',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mail marketing opt-out'),
        ),
    ]
