# Generated by Django 3.2.12 on 2022-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_student_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicile',
            name='in_uk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domicile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='domicile',
            name='is_in_eu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domicile',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
