# Generated by Django 3.2.13 on 2022-04-28 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_nationality_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethnicity',
            name='data_futures_code',
            field=models.CharField(default=99, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentaleducation',
            name='data_futures_code',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='religion',
            name='data_futures_code',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sexualorientation',
            name='data_futures_code',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='parental_education',
            field=models.ForeignKey(db_column='parental_education', default=7, help_text='Do any of your parents (natural, adoptive, step- or guardians who brought you up) have any higher education qualifications, such as a degree, diploma or certificate of higher education?', on_delete=django.db.models.deletion.DO_NOTHING, to='student.parentaleducation'),
        ),
    ]
