# Generated by Django 3.2.12 on 2022-03-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'New feature'), (2, 'Alert'), (3, 'Other')])),
                ('publish', models.DateField()),
                ('unpublish', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'banner',
                'ordering': ['-publish'],
            },
        ),
    ]
