# Generated by Django 3.2.13 on 2022-04-29 09:28

import datetime

import django.db.models.deletion
from django.db import migrations, models

import apps.hesa_data_futures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete')], default='EMPTY', max_length=32)),
                ('academic_year', models.IntegerField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True)),
                ('filename', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'data_futures_batch',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=50)),
                ('clsdcrs', models.CharField(default='02', max_length=2)),
                ('coursetitle', models.CharField(max_length=255)),
                ('prerequisite', models.CharField(max_length=2)),
                ('qualid', models.CharField(max_length=50)),
                ('ttcid', models.CharField(default='07', max_length=2)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.batch')),
            ],
            options={
                'db_table': 'data_futures_course',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numhus', models.CharField(max_length=50)),
                ('engexpectedenddate', models.DateField()),
                ('engstartdate', models.DateField()),
                ('feeelig', models.CharField(max_length=2)),
                ('rcstdnt', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'data_futures_engagement',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modid', models.CharField(max_length=50)),
                ('crdtpts', models.IntegerField()),
                ('crdtscm', models.CharField(default='01', max_length=2)),
                ('fte', models.DecimalField(decimal_places=1, max_digits=4)),
                ('levlpts', models.IntegerField(null=True)),
                ('mtitle', models.CharField(max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.batch')),
            ],
            options={
                'db_table': 'data_futures_module',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualid', models.CharField(max_length=50)),
                ('qualcat', models.CharField(max_length=5)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.batch')),
            ],
            options={
                'db_table': 'data_futures_qualification',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='StudentCourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scsessionid', models.CharField(max_length=50)),
                ('courseid', models.CharField(max_length=50)),
                ('invoicefeeamount', models.IntegerField(null=True)),
                ('invoicehesaid', models.CharField(default='5050', max_length=4, null=True)),
                ('rsnscsend', models.CharField(max_length=2, null=True)),
                ('scsenddate', models.DateField(null=True)),
                ('scsmode', models.CharField(default='31', max_length=2)),
                ('scsstartdate', models.DateField()),
                ('sessionyearid', models.CharField(max_length=50)),
                ('yearprg', models.IntegerField(default=99)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.engagement')),
            ],
            options={
                'db_table': 'data_futures_student_course_session',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueid', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=8)),
                ('venuename', models.CharField(max_length=255)),
                ('venueukprn', models.CharField(default=10007774, max_length=8)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.batch')),
            ],
            options={
                'db_table': 'data_futures_venue',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='StudyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studylocid', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=2, null=True)),
                ('studyproportion', models.IntegerField()),
                ('venueid', models.CharField(max_length=50, null=True)),
                ('student_course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.studentcoursesession')),
            ],
            options={
                'db_table': 'data_futures_study_location',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=17)),
                ('birthdte', models.DateField(null=True)),
                ('ethnic', models.IntegerField(null=True)),
                ('fnames', models.CharField(max_length=100)),
                ('genderid', models.CharField(max_length=2)),
                ('nation', models.CharField(max_length=2)),
                ('ownstu', models.IntegerField()),
                ('religion', models.IntegerField()),
                ('sexid', models.IntegerField()),
                ('sexort', models.IntegerField()),
                ('ssn', models.CharField(max_length=13, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('ttaccom', models.CharField(max_length=2, null=True)),
                ('ttpcode', models.CharField(max_length=8, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.batch')),
            ],
            options={
                'db_table': 'data_futures_student',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='SessionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionyearid', models.CharField(max_length=50)),
                ('syenddate', models.DateField()),
                ('systartdate', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.batch')),
            ],
            options={
                'db_table': 'data_futures_session_year',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='ReferencePeriodStudentLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refperiod', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('rpstuload', models.DecimalField(decimal_places=1, max_digits=4)),
                ('student_course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.studentcoursesession')),
            ],
            options={
                'db_table': 'data_futures_reference_period_student_load',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='QualificationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualsubject', models.IntegerField()),
                ('qualproportion', models.IntegerField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.qualification')),
            ],
            options={
                'db_table': 'data_futures_qualification_subject',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='QualificationAwarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualawardid', models.CharField(max_length=50)),
                ('qualid', models.CharField(max_length=50)),
                ('qualresult', models.CharField(default='0013', max_length=30)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.engagement')),
            ],
            options={
                'db_table': 'data_futures_qualification_awarded',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='ModuleSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modsbj', models.IntegerField()),
                ('modproportion', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.module')),
            ],
            options={
                'db_table': 'data_futures_module_subject',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modinstid', models.CharField(max_length=50)),
                ('continuing', models.CharField(max_length=2, null=True)),
                ('mifeeamount', models.IntegerField(null=True)),
                ('modid', models.CharField(max_length=50)),
                ('modinstenddate', models.DateField(null=True)),
                ('modinststartdate', models.DateField()),
                ('moduleoutcome', models.CharField(max_length=2, null=True)),
                ('student_course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.studentcoursesession')),
            ],
            options={
                'db_table': 'data_futures_module_instance',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='ModuleCostCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costcn', models.IntegerField(null=True)),
                ('costcnproportion', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.module')),
            ],
            options={
                'db_table': 'data_futures_module_cost_centre',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Leaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engenddate', models.DateField()),
                ('rsnengend', models.CharField(max_length=2)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.engagement')),
            ],
            options={
                'db_table': 'data_futures_leaver',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='FundingBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundingbody', models.CharField(max_length=4)),
                ('student_course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.studentcoursesession')),
            ],
            options={
                'db_table': 'data_futures_funding_body',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='FundingAndMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elq', models.CharField(max_length=2, null=True)),
                ('fundcomp', models.CharField(max_length=2, null=True)),
                ('fundlength', models.CharField(default='02', max_length=2)),
                ('nonregfee', models.CharField(default='01', max_length=2)),
                ('student_course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.studentcoursesession')),
            ],
            options={
                'db_table': 'data_futures_funding_and_monitoring',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='EntryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careleaver', models.CharField(default='99', max_length=2, null=True)),
                ('highestqoe', models.CharField(max_length=5, null=True)),
                ('pared', models.IntegerField(null=True)),
                ('permaddcountry', models.CharField(max_length=2)),
                ('permaddpostcode', models.CharField(max_length=8, null=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.engagement')),
            ],
            options={
                'db_table': 'data_futures_entry_profile',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.AddField(
            model_name='engagement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.student'),
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.student')),
            ],
            options={
                'db_table': 'data_futures_disability',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='CourseRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesaid', models.IntegerField(default=10007774)),
                ('roletype', models.IntegerField(default=202)),
                ('crproportion', models.IntegerField(default=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.course')),
            ],
            options={
                'db_table': 'data_futures_course_role',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
        migrations.CreateModel(
            name='AwardingBodyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardingbodyid', models.IntegerField(default=10007774)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesa_data_futures.qualification')),
            ],
            options={
                'db_table': 'data_futures_awarding_body_role',
            },
            bases=(apps.hesa_data_futures.models.XMLStagingModel, models.Model),
        ),
    ]
