# Generated by Django 3.2.10 on 2022-01-18 15:51

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_aim', '0004_alter_qualificationaim_programme'),
        ('student', '0021_auto_20220112_1600'),
        ('module', '0014_delete_waitlist'),
        ('application', '0003_auto_20210722_1228'),
    ]

    operations = [
        migrations.RenameModel('CourseApplication', 'Application')
    ]
