# Generated by Django 3.2.10 on 2022-01-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_aim', '0004_alter_qualificationaim_programme'),
        ('student', '0021_auto_20220112_1600'),
        ('application', '0004_rename_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='native',
            new_name='native_speaker',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='previous_name',
            new_name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='attachment_name_1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_billing_same_as_postal',
        ),
        migrations.RemoveField(
            model_name='application',
            name='residence',
        ),
        migrations.AddField(
            model_name='application',
            name='domicile',
            field=models.ForeignKey(db_column='residence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.domicile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='academic_credit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='disability',
            field=models.ForeignKey(blank=True, db_column='disability', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.disability'),
        ),
        migrations.AlterField(
            model_name='application',
            name='entry_qualification',
            field=models.ForeignKey(blank=True, db_column='entry_qualification', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qualification_aim.entryqualification'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ethnicity',
            field=models.ForeignKey(db_column='ethnicity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.ethnicity'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.ForeignKey(db_column='nationality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.nationality'),
        ),
        migrations.AlterField(
            model_name='application',
            name='native_speaker',
            field=models.BooleanField(blank=True, db_column='native', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='religion',
            field=models.ForeignKey(db_column='religion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.religion'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='filename', max_length=50)),
                ('filename', models.CharField(db_column='attachment', max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', related_query_name='attachment', to='application.application')),
            ],
            options={
                'db_table': 'course_application_attachment',
            },
        ),
    ]
