# Generated by Django 3.0.11 on 2021-01-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('number', models.IntegerField(unique=True)),
                ('prefix', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('fao', models.CharField(blank=True, max_length=128, null=True)),
                ('invoiced_to', models.CharField(blank=True, max_length=128, null=True)),
                ('line1', models.CharField(blank=True, max_length=128, null=True)),
                ('line2', models.CharField(blank=True, max_length=128, null=True)),
                ('line3', models.CharField(blank=True, max_length=128, null=True)),
                ('town', models.CharField(blank=True, max_length=64, null=True)),
                ('countystate', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('custom_narrative', models.BooleanField()),
                ('narrative', models.TextField(blank=True, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=64, null=True)),
                ('division', models.IntegerField(blank=True, null=True)),
                ('allocation', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, db_column='duedate', null=True)),
                ('contact_person', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('company', models.CharField(blank=True, max_length=128, null=True)),
                ('formatted_addressee', models.TextField(blank=True, null=True)),
                ('referred', models.BooleanField()),
                ('vat_no', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': '[app].[invoice]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '[app].[invoice_ledger]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('finance_code', models.CharField(blank=True, max_length=64, null=True)),
                ('narrative', models.CharField(blank=True, max_length=128, null=True)),
                ('allocation', models.IntegerField(blank=True, null=True)),
                ('ref_no', models.IntegerField(blank=True, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '[app].[ledger]',
                'managed': False,
            },
        ),
    ]
