# Generated by Django 3.0.11 on 2021-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
                ('is_cash', models.BooleanField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': '[app].[transaction_type]',
                'managed': False,
            },
        ),
    ]
