# Generated by Django 3.2.5 on 2021-07-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentplantype',
            options={'ordering': ('payments_due', 'deposit', 'payments')},
        ),
    ]
