# Generated by Django 3.2.7 on 2021-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_paymentplantype_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='division',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='formatted_addressee',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact_person',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact_phone',
            field=models.CharField(max_length=64),
        ),
    ]
