# Generated by Django 3.0.11 on 2021-02-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_populate_module_status'),
        ('invoice', '0002_transactiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('payments', models.IntegerField(blank=True, null=True)),
                ('payments_due', models.CharField(blank=True, max_length=32, null=True)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('default_plan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_plan_type',
            },
        ),
        migrations.CreateModel(
            name='ModulePaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, to='module.Module')),
                ('plan_type', models.ForeignKey(db_column='plan_type', on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.PaymentPlanType')),
            ],
            options={
                'db_table': 'module_payment_plan',
            },
        ),
    ]
