# Generated by Django 3.0.14 on 2021-05-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210506_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='account',
            field=models.CharField(db_column='account', max_length=4),
            preserve_default=False,
        ),
    ]
