# Generated by Django 3.0.13 on 2021-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_populate_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='prefix',
            field=models.CharField(default='XG', max_length=32),
        ),
    ]
