# Generated by Django 3.2.5 on 2021-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210630_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiced_to',
            field=models.CharField(max_length=128, verbose_name='Invoice to'),
        ),
    ]
