# Generated by Django 3.2.8 on 2021-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20211001_2003'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modulepaymentplan',
            constraint=models.UniqueConstraint(fields=('module', 'plan_type'), name='unique_module_payment_plan'),
        ),
    ]
