# Generated by Django 3.2.10 on 2022-01-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_modulepaymentplan_unique_module_payment_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('credit_invoice', 'Can credit an invoice'), ('pay_invoice', 'Can add a payment to an invoice'), ('print_invoice', 'Can print an invoice'), ('upload_rcp', 'Can upload RCP invoice payments')]},
        ),
    ]
