# Generated by Django 3.2.12 on 2022-03-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('payment_ref', models.TextField()),
                ('discount_code', models.TextField(blank=True, null=True)),
                ('event', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('firstname', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('email', models.TextField()),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('address3', models.TextField(blank=True, null=True)),
                ('town', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('postcode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.TextField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.TextField(blank=True, null=True)),
                ('voucher', models.IntegerField(blank=True, null=True)),
                ('voucher_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('student', models.IntegerField(blank=True, null=True)),
                ('enrolment', models.IntegerField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('firstname', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('hash_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('entry_qualification', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('fees', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('domicile', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_item',
                'managed': False,
            },
        ),
    ]
