# Generated by Django 3.0.11 on 2021-02-05 21:16

import apps.main.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210125_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to=apps.main.models.PathAndRename('images/staff_profile/')),
        ),
    ]
