# Generated by Django 3.0.11 on 2021-02-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210205_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
    ]
