# Generated by Django 3.0.14 on 2021-06-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='feeregime',
        ),
        migrations.AddField(
            model_name='entryprofile',
            name='pared',
            field=models.IntegerField(blank=True, db_column='PARED', default=7, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='genderid',
            field=models.CharField(blank=True, db_column='GENDERID', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sexort',
            field=models.CharField(blank=True, db_column='SEXORT', max_length=2, null=True),
        ),
    ]
