# Generated by Django 3.0.14 on 2021-06-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesa', '0002_2021_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hecossubject',
            options={'ordering': ('name',)},
        ),
    ]
