# Generated by Django 3.2.6 on 2021-08-16 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesa', '0003_auto_20210626_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulehecossubject',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
