# Generated by Django 3.2.12 on 2022-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesa', '0004_alter_modulehecossubject_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationsawarded',
            name='qual_class',
            field=models.CharField(blank=True, db_column='CLASS', default=16, max_length=2, null=True),
        ),
    ]
