# Generated by Django 3.2.13 on 2022-04-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesa', '0005_qualificationsawarded_qual_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hecossubject',
            options={'ordering': ('name',), 'verbose_name': 'HECoS subject'},
        ),
        migrations.AlterModelOptions(
            name='hesacostcentre',
            options={'ordering': ('description',), 'verbose_name': 'HESA cost centre'},
        ),
        migrations.AlterModelOptions(
            name='programmehecossubject',
            options={'ordering': ('programme', 'hecos_subject'), 'verbose_name': 'Programme HECoS subject'},
        ),
    ]
