# Generated by Django 3.2.12 on 2022-03-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesa', '0005_qualificationsawarded_qual_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryprofile',
            name='batch',
            field=models.ForeignKey(db_column='batch', on_delete=django.db.models.deletion.CASCADE, to='hesa.batch'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='batch',
            field=models.ForeignKey(db_column='batch', on_delete=django.db.models.deletion.CASCADE, to='hesa.batch'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='batch',
            field=models.ForeignKey(db_column='batch', on_delete=django.db.models.deletion.CASCADE, to='hesa.batch'),
        ),
        migrations.AlterField(
            model_name='module',
            name='batch',
            field=models.ForeignKey(db_column='batch', on_delete=django.db.models.deletion.CASCADE, to='hesa.batch'),
        ),
        migrations.AlterField(
            model_name='modulesubject',
            name='batch',
            field=models.ForeignKey(db_column='batch', on_delete=django.db.models.deletion.CASCADE, to='hesa.batch'),
        ),
        migrations.AlterField(
            model_name='qualificationsawarded',
            name='batch',
            field=models.ForeignKey(db_column='batch', on_delete=django.db.models.deletion.CASCADE, to='hesa.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(db_column='batch', on_delete=django.db.models.deletion.CASCADE, to='hesa.batch'),
        ),
        migrations.AlterField(
            model_name='studentonmodule',
            name='batch',
            field=models.ForeignKey(db_column='batch', on_delete=django.db.models.deletion.CASCADE, to='hesa.batch'),
        ),
    ]
