# Generated by Django 3.0.11 on 2021-02-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='division',
            field=models.ForeignKey(db_column='division', default=1, limit_choices_to=models.Q(('id__gt', 8), ('id__lt', 5), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='programme.Division'),
        ),
        migrations.AddField(
            model_name='module',
            name='portfolio',
            field=models.ForeignKey(db_column='portfolio', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='programme.Portfolio'),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.ForeignKey(db_column='status', default=10, on_delete=django.db.models.deletion.DO_NOTHING, to='module.ModuleStatus'),
        ),
    ]
