# Generated by Django 3.0.14 on 2021-06-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20210506_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingtype',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='moduleformat',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='area',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
