# Generated by Django 3.0.11 on 2021-02-04 16:34

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'module_status.yaml', verbosity=2)
    call_command('loaddata', 'division.yaml', verbosity=2)
    call_command('loaddata', 'portfolio.yaml', verbosity=2)


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_add_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
