# Generated by Django 3.0.11 on 2021-02-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0004_auto_20210211_1416'),
        ('invoice', '0003_modulepaymentplan_paymentplantype'),
        ('student', '__first__'),
        ('module', '0003_populate_module_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'book_status',
            },
        ),
        migrations.AddField(
            model_name='fee',
            name='catering_bookings',
            field=models.ManyToManyField(through='enrolment.Catering', to='enrolment.Enrolment'),
        ),
        migrations.AddField(
            model_name='module',
            name='payment_plans',
            field=models.ManyToManyField(through='invoice.ModulePaymentPlan', to='invoice.PaymentPlanType'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='ModuleWaitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('emailed_on', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, related_name='waitlist', to='module.Module')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
            ],
            options={
                'db_table': 'module_waitlist',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=24)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('solo_link', models.TextField(blank=True, null=True)),
                ('isbn_shelfmark', models.TextField(blank=True, db_column='ISBN_shelfmark', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('library_note', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='module.Module')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='module.BookStatus')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
