# Generated by Django 3.0.11 on 2021-02-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '__first__'),
        ('enrolment', '0004_auto_20210211_1416'),
        ('invoice', '0001_initial'),
        ('module', '0003_populate_module_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'book_status',
            },
        ),
        migrations.CreateModel(
            name='MarketingType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'marketing_type',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('area', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.RenameField(
            model_name='module',
            old_name='application',
            new_name='how_to_apply',
        ),
        migrations.AddField(
            model_name='fee',
            name='catering_bookings',
            field=models.ManyToManyField(through='enrolment.Catering', to='enrolment.Enrolment'),
        ),
        migrations.AddField(
            model_name='module',
            name='payment_plans',
            field=models.ManyToManyField(through='invoice.ModulePaymentPlan', to='invoice.PaymentPlanType'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='how_to_apply',
            field=models.TextField(blank=True, db_column='application', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='ModuleWaitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('emailed_on', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, related_name='waitlist', to='module.Module')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
            ],
            options={
                'db_table': 'module_waitlist',
            },
        ),
        migrations.CreateModel(
            name='ModuleSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, to='module.Module')),
                ('subject', models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.DO_NOTHING, to='module.Subject')),
            ],
            options={
                'db_table': 'module_subject',
                'unique_together': {('module', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ModuleMarketingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_type', models.ForeignKey(db_column='marketing_type', on_delete=django.db.models.deletion.DO_NOTHING, to='module.MarketingType')),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, to='module.Module')),
            ],
            options={
                'db_table': 'module_marketing_type',
                'unique_together': {('module', 'marketing_type')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=24)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('solo_link', models.TextField(blank=True, null=True)),
                ('isbn_shelfmark', models.TextField(blank=True, db_column='ISBN_shelfmark', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('library_note', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='module.Module')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='module.BookStatus')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='marketing_types',
            field=models.ManyToManyField(through='module.ModuleMarketingType', to='module.MarketingType'),
        ),
        migrations.AddField(
            model_name='module',
            name='subjects',
            field=models.ManyToManyField(through='module.ModuleSubject', to='module.Subject'),
        ),
    ]
