# Generated by Django 3.2.5 on 2021-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('module', '0003_auto_20210626_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='payment_plans',
            field=models.ManyToManyField(through='invoice.ModulePaymentPlan', to='invoice.PaymentPlanType'),
        ),
    ]
