# Generated by Django 3.0.13 on 2021-04-04 20:05

import apps.core.utils.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20210218_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='terms_and_conditions',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=apps.core.utils.models.UpperCaseCharField(help_text='For details on codes, see <link>', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]\\d{2}[A-Z]\\d{3}[A-Z]\\w[A-Z]$', message='Must be in the form A12B345CDE')]),
        ),
    ]
