# Generated by Django 3.0.11 on 2021-02-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20210211_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'marketing_type',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('area', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.RenameField(
            model_name='module',
            old_name='application',
            new_name='how_to_apply',
        ),
        migrations.AlterField(
            model_name='module',
            name='how_to_apply',
            field=models.TextField(blank=True, db_column='application', null=True),
        ),
        migrations.CreateModel(
            name='ModuleSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, to='module.Module')),
                ('subject', models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.DO_NOTHING, to='module.Subject')),
            ],
            options={
                'db_table': 'module_subject',
                'unique_together': {('module', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ModuleMarketingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_type', models.ForeignKey(db_column='marketing_type', on_delete=django.db.models.deletion.DO_NOTHING, to='module.MarketingType')),
                ('module', models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, to='module.Module')),
            ],
            options={
                'db_table': 'module_marketing_type',
                'unique_together': {('module', 'marketing_type')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='marketing_types',
            field=models.ManyToManyField(through='module.ModuleMarketingType', to='module.MarketingType'),
        ),
        migrations.AddField(
            model_name='module',
            name='subjects',
            field=models.ManyToManyField(through='module.ModuleSubject', to='module.Subject'),
        ),
    ]
