# Generated by Django 3.2.6 on 2021-08-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20210722_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('name',)},
        ),
    ]
