# Generated by Django 3.0.13 on 2021-04-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20210404_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='is_compulsory',
        ),
        migrations.AlterField(
            model_name='fee',
            name='credit_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='eu_fee',
            field=models.BooleanField(db_column='eufee', default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_catering',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_payable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_single_accom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_twin_accom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
