# Generated by Django 3.0.14 on 2021-05-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_auto_20210405_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ('display_order',)},
        ),
        migrations.RemoveField(
            model_name='fee',
            name='account',
        ),
        migrations.AlterField(
            model_name='fee',
            name='allocation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='credit_fee',
            field=models.BooleanField(default=False, help_text='Additional fee to take a weekly class for credit'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='end_date',
            field=models.DateField(
                blank=True, help_text='Optional: day on which to remove the fee from the website', null=True
            ),
        ),
        migrations.AlterField(
            model_name='fee',
            name='eu_fee',
            field=models.BooleanField(
                db_column='eufee', default=False, help_text='Only payable by Home/EU students?', verbose_name='Home/EU'
            ),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_catering',
            field=models.BooleanField(default=False, help_text='Includes catering', verbose_name='Catering'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_payable',
            field=models.BooleanField(
                default=True, help_text='Make this fee payable on the website', verbose_name='Payable'
            ),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_single_accom',
            field=models.BooleanField(
                default=False, help_text='Includes a single accommodation', verbose_name='Single accommodation'
            ),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_twin_accom',
            field=models.BooleanField(
                default=False, help_text='Includes a double accommodation', verbose_name='Double accommodation'
            ),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_visible',
            field=models.BooleanField(
                default=True, help_text='Make this fee visible on the website', verbose_name='Visible'
            ),
        ),
        migrations.AlterField(
            model_name='fee',
            name='limit',
            field=models.IntegerField(blank=True, help_text='Todo: Manage limits link', null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='type',
            field=models.ForeignKey(
                db_column='type',
                default=7,
                limit_choices_to={'is_active': True},
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='module.FeeType',
            ),
        ),
    ]
