# Generated by Django 3.2.7 on 2021-09-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_auto_20210816_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='double_places',
        ),
        migrations.RemoveField(
            model_name='module',
            name='reading_list_links',
        ),
        migrations.RemoveField(
            model_name='module',
            name='reading_list_url',
        ),
        migrations.AddField(
            model_name='module',
            name='direct_enrolment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='cost_centre',
            field=models.CharField(blank=True, help_text='Cost centre, activity code and source of funds form the finance code', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='custom_fee',
            field=models.CharField(blank=True, help_text='Only used in the course summary box (replaces the automatic fees section on the website)', max_length=1012, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='default_non_credit',
            field=models.BooleanField(default=False, help_text='Online enrolments will have this status by default', verbose_name='Default status'),
        ),
        migrations.AlterField(
            model_name='module',
            name='enrol_online',
            field=models.BooleanField(blank=True, null=True, verbose_name='Online enrolment'),
        ),
        migrations.AlterField(
            model_name='module',
            name='format',
            field=models.ForeignKey(blank=True, db_column='format', help_text='Tells the student how they will study', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='module.moduleformat'),
        ),
        migrations.AlterField(
            model_name='module',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Optional. It is better to provide start and end times'),
        ),
        migrations.AlterField(
            model_name='module',
            name='no_search',
            field=models.BooleanField(default=False, verbose_name='Hide from search results'),
        ),
        migrations.AlterField(
            model_name='module',
            name='non_credit_bearing',
            field=models.BooleanField(default=True, verbose_name='Credit bearing'),
        ),
        migrations.AlterField(
            model_name='module',
            name='notification',
            field=models.CharField(blank=True, help_text='A message that appears atop the page, announcing change of tutor, date, location, etc.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='scholarships',
            field=models.TextField(blank=True, null=True, verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='module',
            name='selection_criteria',
            field=models.TextField(blank=True, null=True, verbose_name='Entry requirements'),
        ),
        migrations.AlterField(
            model_name='module',
            name='single_places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Single rooms'),
        ),
        migrations.AlterField(
            model_name='module',
            name='snippet',
            field=models.CharField(blank=True, help_text='Used in cards and search results. Maximum 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='teaching_outcomes',
            field=models.TextField(blank=True, null=True, verbose_name='Learning outcomes'),
        ),
        migrations.AlterField(
            model_name='module',
            name='twin_places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Twin rooms'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.SlugField(blank=True, help_text='Leave empty to automatically generate from the title', max_length=256, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='module',
            name='week_number',
            field=models.IntegerField(blank=True, help_text='For multi-week summer schools', null=True),
        ),
    ]
