# Generated by Django 3.2.7 on 2021-10-01 20:03

import apps.core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_alter_module_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='phone',
            field=apps.core.utils.models.PhoneField(blank=True, max_length=256, null=True),
        ),
    ]
