# Generated by Django 3.2.9 on 2021-11-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0011_auto_20211001_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('bookable', models.BooleanField(default=True)),
                ('building', models.CharField(max_length=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'room',
                'ordering': ['building', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('building', 'city')},
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='room_setup',
            field=models.CharField(blank=True, choices=[('SEMINR', 'Seminar'), ('ECTR', 'Computer teaching'), ('BOARD', 'Boardroom'), ('CLASS', 'Classroom'), ('LECT', 'Lecture'), ('UCHRS', 'U of chairs'), ('UTBLS', 'U of tables')], max_length=12),
        ),
        migrations.AlterField(
            model_name='module',
            name='room',
            field=models.ForeignKey(blank=True, db_column='room', null=True, on_delete=django.db.models.deletion.PROTECT, to='module.room'),
        ),
    ]
