# Generated by Django 3.2.10 on 2022-01-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0012_auto_20211111_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'base_manager_name': 'objects', 'permissions': [('upload_to_cabs', 'Can upload module booking details to CABS')]},
        ),
    ]
