# Generated by Django 3.2.10 on 2022-01-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0013_alter_module_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Waitlist',
                ),
            ],
            database_operations=[]
        ),
    ]
