# Generated by Django 3.2.12 on 2022-03-17 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0016_alter_module_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='hash',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, null=True),
        ),
    ]
