# Generated by Django 3.2.12 on 2022-03-28 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0017_module_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='additional_information',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_shelfmark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ISBN / library shelfmark'),
        ),
        migrations.AlterField(
            model_name='book',
            name='solo_link',
            field=models.CharField(blank=True, max_length=512, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[(None, '– Select –'), ('Preparatory reading', 'Preparatory reading'), ('Course reading', 'Course reading')], max_length=24),
        ),
    ]
