# Generated by Django 3.0.14 on 2021-05-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('points_awarded', models.IntegerField(blank=True, null=True)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('transcript_date', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'enrolment',
            },
        ),
        migrations.CreateModel(
            name='EnrolmentResult',
            fields=[
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('hesa_code', models.CharField(max_length=1)),
                ('allow_certificate', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enrolment_result',
            },
        ),
        migrations.CreateModel(
            name='EnrolmentStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('takes_place', models.BooleanField()),
                ('is_debtor', models.BooleanField()),
                ('on_hesa_return', models.BooleanField()),
            ],
            options={
                'db_table': 'enrolment_status',
            },
        ),
    ]
