# Generated by Django 3.0.11 on 2021-02-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
        ('enrolment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='module',
            field=models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrolments', to='module.Module'),
        ),
    ]
