# Generated by Django 3.0.11 on 2021-02-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrolment', '0002_enrolment_module'),
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='qa',
            field=models.ForeignKey(blank=True, db_column='qa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='programme.QA'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='result',
            field=models.ForeignKey(db_column='result', on_delete=django.db.models.deletion.DO_NOTHING, to='enrolment.EnrolmentResult'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='enrolment.EnrolmentStatus'),
        ),
    ]
