# Generated by Django 3.0.14 on 2021-05-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_auto_20210513_0856'),
        ('module', '0002_auto_20210506_1039'),
        ('enrolment', '0002_auto_20210506_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='module',
            field=models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrolments', related_query_name='enrolment', to='module.Module'),
        ),
    ]
