# Generated by Django 3.0.11 on 2021-02-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_populate_module_status'),
        ('enrolment', '0003_add_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='enrolmentresult',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='enrolmentresult',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=8, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('enrolment', models.ForeignKey(db_column='enrolment', on_delete=django.db.models.deletion.DO_NOTHING, related_name='catering', to='enrolment.Enrolment')),
                ('fee', models.ForeignKey(db_column='fee', on_delete=django.db.models.deletion.DO_NOTHING, related_name='catering', to='module.Fee')),
            ],
            options={
                'db_table': 'catering',
            },
        ),
    ]
