# Generated by Django 3.0.14 on 2021-06-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_aim', '0001_initial'),
        ('enrolment', '0003_auto_20210513_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='qa',
            field=models.ForeignKey(
                blank=True,
                db_column='qa',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='qualification_aim.QualificationAim',
            ),
        ),
    ]
