# Generated by Django 3.0.14 on 2021-06-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_aim', '0001_initial'),
        ('enrolment', '0004_auto_20210614_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='qa',
            field=models.ForeignKey(db_column='qa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrolments', related_query_name='enrolment', to='qualification_aim.QualificationAim'),
        ),
    ]
