# Generated by Django 3.0.11 on 2021-02-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0005_populate_enrolment_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='no_image_consent',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='provenance_details',
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='result',
            field=models.ForeignKey(db_column='result', default=7, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='enrolment.EnrolmentResult'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='transcript_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='enrolmentresult',
            name='hesa_code',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='enrolmentresult',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
