# Generated by Django 3.2.7 on 2021-09-29 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_alter_module_terms_and_conditions'),
        ('qualification_aim', '0001_squashed_0004'),
        ('enrolment', '0006_auto_20210820_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='module',
            field=models.ForeignKey(db_column='module', on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', related_query_name='enrolment', to='module.module'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='qa',
            field=models.ForeignKey(db_column='qa', on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', related_query_name='enrolment', to='qualification_aim.qualificationaim', verbose_name='Qualification aim'),
        ),
    ]
