# Generated by Django 3.2.13 on 2022-04-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0007_auto_20210929_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolmentresult',
            name='data_futures_outcome',
            field=models.CharField(default='', max_length=2, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolmentresult',
            name='data_futures_result',
            field=models.CharField(default='', max_length=2, null=True),
            preserve_default=False,
        ),
    ]
